# Generated by Django 5.2.2 on 2025-06-11 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('contacto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'reservas_cliente',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('contacto', models.CharField(max_length=20)),
                ('marca_carro', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reservas_conductor',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('destino', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.conductor')),
            ],
            options={
                'db_table': 'reservas_reservacion',
            },
        ),
    ]
